services:
  torrentflow:
    build: .
    container_name: torrentflow_app
    ports:
      - "5000:5000"
    volumes:
      - ./torrents.db:/app/torrents.db
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - QBIT_HOST=192.168.3.30
      - QBIT_PORT=8080
      - QBIT_USER=admin
      - QBIT_PASS=adminadmin